version: 1.0.{build}
os: Previous Visual Studio 2017
install:
- git submodule update --init --recursive
build_script:
- gradlew.bat -is nunit nugetPack
test: off
artifacts:
  - path: 'build\distributions\*.nupkg'
    name: Nuget
